### ISSUE TITLE
endgame training games

### ISSUE THREAD

**Issue by ivarcode** [ivarcode/schackmatt#108]
**Problem / Catalyst**
We want content!

**Describe the solution you'd like**
Endgame puzzles as discussed from this email (text below)

**From Nick Groh**
Focus on the endgames, broken up by piece theme:
pawn
queen
king
bishop
knight
rook
Here's the pawn article which links to the square article in more depth as a starting point.

I pulled the pawn endgames from this study, but I can make unique studies if needed in the future (it's how I planned to make them for each piece)

**Comment by ivarcode** [comment]
coordinates on board

**Comment by ragnarok5375** [comment]
Did I find the right issue?

**Comment by ivarcode** [comment]
Let's have (for each exercise), opponent play the first move.

**Comment by ragnarok5375** [comment]
> Let's have (for each exercise), opponent play the first move.

Can you explain why?  Does this mean it starts and the opponent moves right away and then you go?  So you can see the last move first?

**Comment by ivarcode** [comment]
> > Let's have (for each exercise), opponent play the first move.
> 
> Can you explain why?  Does this mean it starts and the opponent moves right away and then you go?  So you can see the last move first?

Yeah, just popped into my head. I'm used to (for example lichess puzzles, play one move when the puzzle loads to put you into the game). This is actually very important if en passant is involved but it would be good to get into the habit of doing this. Just wanted to make a note here. Back to my day job now :P
