### ISSUE TITLE
board size bug (on mobile?)

### ISSUE THREAD

**Issue by ragnarok5375** [ivarcode/schackmatt#113]
Hi

Only one part of the board is showing, we need to resize the board. But after it’s ok but the text size is too small.

Best regard

FOUAD

**Comment by ivarcode** [comment]
Let's give useful titles to issues we create, like this maybe? ^

Can you get a little more detail from this person before we make an issue? I have no support for mobile right now, which might be what he was running into (if you open this site on your phone, the board will be way too big).  If this is the case, we should not create this new issue for it, instead we should make any new notes on our other issue #87 (and I will make this issue as duplicate / wontfix

**Comment by ragnarok5375** [comment]
I made a new issue because I figured multiple people were going to leave feedback and it would be a good place to have it all in one place.  I didn't look through to see what issues existed.  It's gonna take some time for me to get used to this workflow since it's new to me so just let me know if stuffs put in the wrong place like you ddi here.

What action is needed for this?  Did you already move this to the right place?

Also, is there a place for overall timelines of when certain things will be done and which will be done at another time?  Maybe it's here somewhere I'm not aware of.

**Comment by ivarcode** [comment]
If you plan to take notes from users in one place and not do individual issues, all good, let's for now, start by creating a document on Drive or some email chain between us and we can call and break them into issues together later on. For now, I will make new issues, until you get the hang of what bugs / feedback warrant issue creation (that said you can still update stuff like #108 

Make a note here when you understand this, and then I will take action on this issue to mark it off so we don't see it again, and we can switch to Drive and off-github communication for the time being.

**Comment by ragnarok5375** [comment]
Sounds good.  You said to use Github so I tried to use it, but that makes sense too.

Sounds like we'll have updates to be done here and backlog items via Drive.
