### ISSUE TITLE
opening trainer

### ISSUE THREAD

**Issue by ivarcode** [ivarcode/schackmatt#14]
- options for user to replay same opening over and over to practice
- option for user to choose favorite lines and save them to profile

- [x] add debugging tool for us to see and read opening lines so we don't have to learn the opening to test it lol
- [x] case for end of opening theory
- [x] integrate occasional message (explanation)
- [x] indicate loading JSON animation using bootstrap spinner

**Comment by ivarcode** [comment]
progress made, interface work next

**Comment by ivarcode** [comment]
Possible coordination with #20

**Comment by ragnarok5375** [comment]
When the user is out of the opening line, I think having the option to "continue playing against computer" or "Go back to explore another line" could be a good option @ivarcode

**Comment by ivarcode** [comment]
> When the user is out of the opening line, I think having the option to "continue playing against computer" or "Go back to explore another line" could be a good option @ivarcode

Until we have a computer that actually works, we shouldn't do this.  But, having this in the backlog and having a disabled button that says "play vs computer" hover text "coming soon" and then an enabled button saying "good job, start opening again!" would be good I think?

**Comment by ragnarok5375** [comment]
Agreed with your suggestion.  

I'm down with any feature users would "expect" that we don't have capacity for at this time to say "coming soon".  We can also have some sort of form on the side that says "is something missing?" to report bugs and suggestions
