### ISSUE TITLE
you can move your opponent's pieces

### ISSUE THREAD

**Issue by cristian-5** [ivarcode/schackmatt#152]
**Describe the bug**
You can move your opponent's pieces in endgame trainer.

**To Reproduce**
When trying to solve an engame-trainer position, as soon as you make a move, drag your opponent's king on one legal square and if you're fast enough it will obey you. Sound like black magic is going on under the hood.

**Expected behavior**
So, in a game, usually, you should only be able to move when it's your turn. If you don't do so it's not super polite and sometimes (when someone notices) could be considered cheating.

**Comment by ivarcode** [comment]
This was actually not even considered until recently.  An analysis board, for example, allows you to move both colors.

https://github.com/ivarcode/schackmatt/pull/156 is actually the solution I am already working on to solve this.  Marking this `wont-fix` but good note.
