### ISSUE TITLE
Dropdown problems

### ISSUE THREAD

**Issue by cristian-5** [ivarcode/schackmatt#166]
**Describe the bug**
The dropdown features visually incompatible style properties.
The items are not properly aligned. That causes the menu to have a double edge effect.

<img width="309" alt="Screenshot 2021-04-03 at 23 15 27" src="https://user-images.githubusercontent.com/30161685/113491713-00f50500-94d3-11eb-8519-13970e42f2e7.png">

**FIX**
I will fix this, add a new shadow and give it a sharper style. I might also fix the dropdown arrow.

**Comment by ivarcode** [comment]
Nice job!
