### ISSUE TITLE
About page update

### ISSUE THREAD

**Issue by cristian-5** [ivarcode/schackmatt#169]
**Problem / Catalyst**
The about page needs some tweaks here and there.
There's too much text in just one spot.

**Comment by cristian-5** [comment]
<img width="1485" alt="Screenshot 2021-04-06 at 20 21 07" src="https://user-images.githubusercontent.com/30161685/113759818-d1820a80-9715-11eb-9406-af148d8c9e83.png">

**Comment by ivarcode** [comment]
This has since been resolved via a different branch.
