### ISSUE TITLE
Movement sluggishness 

### ISSUE THREAD

**Issue by N-Holm** [ivarcode/schackmatt#26]
It appears that the yellow highlighter over the board squares gets shown to the user before the piece is actually on the square. If you where to put the mouse right on the edge of a new square just after the highlighter selected it, the piece will stay in-between squares until the mouse moves into the square more.

**Comment by ivarcode** [comment]
it could be useful to confirm this by writing log statements when these events happen in the code...
maybe you @N-Holm  would want to make a branch to test this out and print out something specifically when a square is highlighted vs when the board is redrawn after a piece is dropped (to see which comes first)?

**Comment by ivarcode** [comment]
@N-Holm says this is no longer a problem bc i fixed it on accident woo
