### ISSUE TITLE
About page 

### ISSUE THREAD

**Issue by N-Holm** [ivarcode/schackmatt#85]
**Is your feature request related to a problem? Please describe.**
The users will not know who's working on the website and where to send important information such as about bugs

**Describe the solution you'd like**
A page that shows the user what the website is about as well as who the contributors are.

**Comment by N-Holm** [comment]
Note to self:
real photo / goofy photo: when user hovers over real photo in the about page the goofy photo ill slide in

**Comment by ivarcode** [comment]
@N-Holm this will move to "done" in triage when you close the issue.. is this issue finished?  we merged #95 ...
